// <auto-generated />
using System;
using ConsegnePoltrone.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsegnePoltrone.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260524090413_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsegnePoltrone.Models.Consegna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClienteCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteCitta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteIndirizzo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteProvincia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteTelefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEffettivaConsegna")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataOrdine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPrevistaConsegna")
                        .HasColumnType("datetime2");

                    b.Property<string>("Esito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FasciaAlle")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FasciaDalle")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ImportoDaPagare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ModalitaPagamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoteConsegna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoteInterne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroOrdine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("PagamentoRicevuto")
                        .HasColumnType("bit");

                    b.Property<string>("ProdottoCodice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdottoDescrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdottoNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantita")
                        .HasColumnType("int");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrasportatoreId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TrasportatoreId");

                    b.ToTable("Consegne");
                });

            modelBuilder.Entity("ConsegnePoltrone.Models.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsegnaId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DimensioneBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("NomeFileOriginale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeFileSalvato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UploadedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConsegnaId");

                    b.HasIndex("UploadedById");

                    b.ToTable("Documenti");
                });

            modelBuilder.Entity("ConsegnePoltrone.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ConsegnePoltrone.Models.Consegna", b =>
                {
                    b.HasOne("ConsegnePoltrone.Models.User", "Trasportatore")
                        .WithMany("ConsegneAssegnate")
                        .HasForeignKey("TrasportatoreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Trasportatore");
                });

            modelBuilder.Entity("ConsegnePoltrone.Models.Documento", b =>
                {
                    b.HasOne("ConsegnePoltrone.Models.Consegna", "Consegna")
                        .WithMany("Documenti")
                        .HasForeignKey("ConsegnaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsegnePoltrone.Models.User", "UploadedBy")
                        .WithMany("DocumentiCaricati")
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consegna");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("ConsegnePoltrone.Models.Consegna", b =>
                {
                    b.Navigation("Documenti");
                });

            modelBuilder.Entity("ConsegnePoltrone.Models.User", b =>
                {
                    b.Navigation("ConsegneAssegnate");

                    b.Navigation("DocumentiCaricati");
                });
#pragma warning restore 612, 618
        }
    }
}
